#-------------------------------------#
#   请选择对应的环境env值来切换参数   #
#-------------------------------------#
#env=yu1
#env=ysi
env=ydt
case $env in
yu1)
pipeline_name=yu1_dat_hds
hds_odps_project=yu1_dat_hds
ods_odps_project=ect888_ods_uat1
odps_accessId=d5acUDf6Na5MkpuQ
odps_accessKey=NUTTli5EicRL13hkv65jjgKn7FF6A5
ots_endpoint=http://YU1-DAT-HDS-OTS.cn-shanghai-zty-d01.ots.dcp.dev.ect-it.com
ots_accessId=q6iC329hNhDnxQuW
ots_accessKey=2TEP4W1b0ASWqdg7TRDdXjqzV4SE5S
ots_instanceName=YU1-DAT-HDS-OTS
mysql_ip=rdspx3ijurs5n22rt6mh8.mysql.rds.dcp.dev.ect-it.com
mysql_db=hdsmgmdb
username=hdsmgmdb
password=admin1234
cdp_odpsreader_mbps=5
;;
ysi)
pipeline_name=ysi_dat_hds
hds_odps_project=ysi_dat_hds
ods_odps_project=ect888_ods
odps_accessId=d5acUDf6Na5MkpuQ
odps_accessKey=NUTTli5EicRL13hkv65jjgKn7FF6A5
ots_endpoint=http://YSI-DAT-HDS-OTS.cn-shanghai-zty-d01.ots.dcp.dev.ect-it.com
ots_accessId=q6iC329hNhDnxQuW
ots_accessKey=2TEP4W1b0ASWqdg7TRDdXjqzV4SE5S
ots_instanceName=YSI-DAT-HDS-OTS
mysql_ip=rds0rxzzaqzg00746uf6j.mysql.rds.dcp.dev.ect-it.com 
mysql_db=hdsmgmdb
username=hdsmgmdb
password=admin1234
cdp_odpsreader_mbps=5
;;
ydt)
pipeline_name=ydt_dat_hds
hds_odps_project=ydt_dat_hds
ods_odps_project=ect888_ods_dev
odps_accessId=d5acUDf6Na5MkpuQ
odps_accessKey=NUTTli5EicRL13hkv65jjgKn7FF6A5
ots_endpoint=http://YDT-DAT-HDS-OTS.cn-shanghai-zty-d01.ots.dcp.dev.ect-it.com
ots_accessId=q6iC329hNhDnxQuW
ots_accessKey=2TEP4W1b0ASWqdg7TRDdXjqzV4SE5S
ots_instanceName=YDT-DAT-HDS-OTS
mysql_ip=rdsd5x34zmdz8bn3fxxay.mysql.rds.dcp.dev.ect-it.com
mysql_db=hdsmgmdb
username=hdsmgmdb
password=admin1234
cdp_odpsreader_mbps=5
;;
esac
