drop table if exists o_ccs_his_fee_trade_credit;
create table if not exists o_ccs_his_fee_trade_credit(
fee_trade_sn     string,                                                         
data_from        string,                                                         
fee_category1    string,                                                         
fee_category2    string,                                                         
biz_serial_no    string,                                                         
channel_serial_no  string,                                                         
currency         string,                                                         
trade_amount     decimal,                                                        
trade_date       string,                                                         
trade_time       string,                                                         
taker            string,                                                         
taker_code       string,                                                         
taker_sub        string,                                                         
transferee       string,                                                         
transferee_code  string,                                                         
transferee_sub   string,                                                         
transferor       string,                                                         
transferor_code  string,                                                      
transferor_sub   string,                                                         
record_status    string,                                                         
trade_type_status  string,                                                         
account_no       string,                                                         
account_type     string,                                                         
detail_type      string,                                                         
compute_status   string,                                                         
remark           string,                                                         
reserve1         string,                                                         
reserve2         string,                                                         
collect_date     string,                                                         
tohis_date       string,                                                         
order_by_no      string)
	partitioned by (dt string);