
	alter table  f_his_ccs_fee_jour_detail drop if     exists partition (dt = '$date_dt');
	alter table  f_his_ccs_fee_jour_detail add  if not exists partition (dt = '$date_dt');

	insert into table  f_his_ccs_fee_jour_detail partition( dt = '$date_dt' )
	select
		
		case when fee_sn is null then '' else fee_sn end,
		case when fee_id is null then '' else fee_id end,
		case when fee_name is null then '' else fee_name end,
		case when fee_type_flag is null then '' else fee_type_flag end,
		case when serial_no is null then '' else serial_no end,
		case when fee_category1 is null then '' else fee_category1 end,
		case when fee_category2 is null then '' else fee_category2 end,
		case when length(trim(occur_date))==10 then concat(concat(substr(occur_date,1,4),substr(occur_date,6,2)),substr(occur_date,9,2)) 
					when occur_date is null then '' else occur_date end,
		case when org_code is null then '' else org_code end,
		case when org_name is null then '' else org_name end,
		case when user_id is null then '' else user_id end,
		case when user_name is null then '' else user_name end,
		case when currency is null then '' else currency end,
		case when occur_amount is null then '' else cast(occur_amount as string)  end,
		case when standard_fare is null then '' else cast (standard_fare as string) end,
		case when fee_amount is null then '' else cast(fee_amount as string)  end,
		case when favorable_amount is null then '' else cast (favorable_amount as string) end,
		case when fee_cycle_id is null then '' else fee_cycle_id end,
		case when fee_detail_id is null then '' else fee_detail_id end,
		case when create_type is null then '' else create_type end,
		case when last_update_date is null then '' else last_update_date end,
		case when last_update_time is null then '' else last_update_time end,
		case when gather_flag is null then '' else gather_flag end,
		case when need_gather is null then '' else need_gather end,
		case when result_code is null then '' else result_code end,
		case when result_info is null then '' else result_info end,
		case when tohis_date is null then '' else tohis_date end,
		case when channel_serial_no is null then '' else channel_serial_no end,
		case when create_date is null then '' else create_date end,
		case when fees_base_type is null then '' else fees_base_type end,
		case when detail_no    is null then '' else detail_no    end,
		case when process_process_id is null then '' else process_process_id end,
		case when process_fee_trade_sn is null then '' else process_fee_trade_sn end,
		case when process_fee_id is null then '' else process_fee_id end,
		case when process_fee_category1 is null then '' else process_fee_category1 end,
		case when process_fee_category2 is null then '' else process_fee_category2 end,
		case when process_fee_org_code is null then '' else process_fee_org_code end,
		case when process_taker_code is null then '' else process_taker_code end,
		case when process_transferee_code is null then '' else process_transferee_code end,
		case when process_transferor_code is null then '' else process_transferor_code end,
		case when process_trade_amount is null then '' else process_trade_amount end,
		case when process_currency is null then '' else process_currency end,
		case when length(trim(process_trade_date))==10 then concat(concat(substr(process_trade_date,1,4),substr(process_trade_date,6,2)),substr(process_trade_date,9,2)) 
					when process_trade_date is null then '' else process_trade_date end,
		case when process_trade_time is null then '' else process_trade_time end,
		case when process_compute_status is null then '' else process_compute_status end,
		case when process_include_count_favorable is null then '' else process_include_count_favorable end,
		case when process_input_date is null then '' else process_input_date end,
		case when process_input_time is null then '' else process_input_time end,
		case when process_remark is null then '' else process_remark end,
		case when process_reserve1 is null then '' else process_reserve1 end,
		case when process_reserve2 is null then '' else process_reserve2 end,
		case when process_tohis_date is null then '' else process_tohis_date end,
		case when process_trading_channel is null then '' else process_trading_channel end,
		case when process_channel_serial_no is null then '' else process_channel_serial_no end,
		case when process_order_by_no is null then '' else process_order_by_no end,
		case when process_multitem_flag is null then '' else process_multitem_flag end,
		case when process_detail_no is null then '' else process_detail_no end,
		case when core_fee_trade_sn is null then '' else core_fee_trade_sn end,
		case when core_fee_category1 is null then '' else core_fee_category1 end,
		case when core_fee_category2 is null then '' else core_fee_category2 end,
		case when core_busi_type is null then '' else core_busi_type end,
		case when core_busi_mark is null then '' else core_busi_mark end,
		case when core_msg_no is null then '' else core_msg_no end,
		case when core_biz_serial_no is null then '' else core_biz_serial_no end,
		case when core_channel_serial_no is null then '' else core_channel_serial_no end,
		case when core_currency is null then '' else core_currency end,
		case when core_trade_amount is null then '' else cast (core_trade_amount as string) end,
		case when length(trim(core_trade_date))==10 then concat(concat(substr(core_trade_date,1,4),substr(core_trade_date,6,2)),substr(core_trade_date,9,2)) 
					when core_trade_date is null then '' else core_trade_date end,
		case when core_trade_time is null then '' else core_trade_time end,
		case when core_taker is null then '' else core_taker end,
		case when core_taker_code is null then '' else core_taker_code end,
		case when core_taker_sub is null then '' else core_taker_sub end,
		case when core_transferee is null then '' else core_transferee end,
		case when core_transferee_code is null then '' else core_transferee_code end,
		case when core_transferee_sub is null then '' else core_transferee_sub end,
		case when core_transferor is null then '' else core_transferor end,
		case when core_transferor_code is null then '' else core_transferor_code end,
		case when core_transferor_sub is null then '' else core_transferor_sub end,
		case when core_record_status is null then '' else core_record_status end,
		case when core_trade_type_status is null then '' else core_trade_type_status end,
		case when core_compute_status is null then '' else core_compute_status end,
		case when core_remark is null then '' else core_remark end,
		case when core_reserve1 is null then '' else core_reserve1 end,
		case when core_reserve2 is null then '' else core_reserve2 end,
		case when core_merchants_type is null then '' else core_merchants_type end,
		case when core_trading_channel is null then '' else core_trading_channel end,
		case when core_collect_date is null then '' else core_collect_date end,
		case when core_orig_busi_type is null then '' else core_orig_busi_type end,
		case when core_orig_busi_mark is null then '' else core_orig_busi_mark end,
		case when core_orig_msg_no is null then '' else core_orig_msg_no end,
		case when core_orig_biz_serial_no is null then '' else core_orig_biz_serial_no end,
		case when core_orig_taker_code is null then '' else core_orig_taker_code end,
		case when core_collect_status is null then '' else core_collect_status end,
		case when core_tohis_date is null then '' else core_tohis_date end,
		case when core_order_by_no is null then '' else core_order_by_no end,
		case when core_detail_no is null then '' else core_detail_no end,
		case when core_orig_detail_no    is null then '' else core_orig_detail_no end  
		
		
		
	from 
	 o_his_ccs_fee_jour_detail
	where dt = 'dtonly';
