drop table if exists o_his_ccs_fee_trade_core_real;
create table if not exists o_his_ccs_fee_trade_core_real(
fee_trade_sn     string,   
fee_category1    string,   
fee_category2    string,   
busi_type        string,   
busi_mark        string,   
msg_no           string,   
biz_serial_no    string,   
channel_serial_no  string, 
currency         string,   
trade_amount     decimal , 
trade_date       string,   
trade_time       string,   
taker            string,   
taker_code       string,   
taker_sub        string,   
transferee       string,   
transferee_code  string,   
transferee_sub   string,   
transferor       string,   
transferor_code  string,   
transferor_sub   string,   
record_status    string,   
trade_type_status  string, 
compute_status   string,   
remark           string,   
reserve1         string,   
reserve2         string,   
merchants_type   string,   
trading_channel  string,   
collect_date     string,   
orig_busi_type   string,   
orig_busi_mark   string,   
orig_msg_no      string,   
orig_biz_serial_no  string,
orig_taker_code  string,   
collect_status   string,   
order_by_no      string,
detail_no        string,                                            
orig_detail_no   string )
	partitioned by (dt string);