
	alter table  o_his_ccs_fee_real_union drop if     exists partition (dt = 'dtonly');
	alter table  o_his_ccs_fee_real_union add  if not exists partition (dt = 'dtonly');

	insert into table  o_his_ccs_fee_real_union partition( dt = 'dtonly' )
	select
		a.fee_sn              ,
		a.fee_id              ,
		a.fee_name            ,
		a.fee_type_flag       ,
		a.serial_no           ,
		a.fee_category1       ,
		a.fee_category2       ,
		a.occur_date          ,
		a.org_code            ,
		a.org_name            ,
		a.user_id             ,
		a.user_name           ,
		a.currency            ,
		a.occur_amount       ,
		a.standard_fare      ,
		a.fee_amount         ,
		a.favorable_amount   ,
		a.fee_cycle_id        ,
		a.fee_detail_id       ,
		a.create_type         ,
		a.last_update_date    ,
		a.last_update_time    ,
		a.gather_flag         ,
		a.need_gather         ,
		a.result_code         ,
		a.result_info         ,
		a.channel_serial_no   ,
		a.create_date         ,
		a.fees_base_type     ,
		a.detail_no   	  ,

		b.process_id      ,  
		b.fee_trade_sn    ,  
		b.fee_id          ,  
		b.fee_category1   ,  
		b.fee_category2   ,  
		b.fee_org_code    ,  
		b.taker_code      ,  
		b.transferee_code ,  
		b.transferor_code ,  
		b.trade_amount    , 
		b.currency        ,  
		b.trade_date      ,  
		b.trade_time      ,  
		b.compute_status  ,  
		b.include_count_favorable ,
		b.input_date      ,  
		b.input_time      ,  
		b.remark          ,  
		b.reserve1        ,  
		b.reserve2        , 
		b.trading_channel ,  
		b.channel_serial_no ,
		b.order_by_no     ,  
		b.multitem_flag   ,
		b.detail_no       ,

		c.fee_trade_sn     ,                                                         
		c.fee_category1    ,                                                         
		c.fee_category2    ,                                                        
		c.busi_type        ,            
		c.busi_mark        ,                                                         
		c.msg_no           ,                                                         
		c.biz_serial_no    ,                                                         
		c.channel_serial_no  ,                                                         
		c.currency         ,                                                         
		c.trade_amount     ,                                                        
		c.trade_date       ,                                                         
		c.trade_time       ,                                                         
		c.taker            ,                                                         
		c.taker_code       ,                                                         
		c.taker_sub        ,                                                         
		c.transferee       ,                                                         
		c.transferee_code  ,                                                         
		c.transferee_sub   ,                                                         
		c.transferor       ,                                                         
		c.transferor_code  ,                                                         
		c.transferor_sub   ,                                                         
		c.record_status    ,                                                         
		c.trade_type_status  ,                                                       
		c.compute_status   ,                                                         
		c.remark           ,                                                         
		c.reserve1         ,                                                        
		c.reserve2         ,                                                         
		c.merchants_type   ,                                                         
		c.trading_channel  ,                                                         
		c.collect_date     ,                                                         
		c.orig_busi_type   ,                                                         
		c.orig_busi_mark   ,                                                         
		c.orig_msg_no      ,                                                         
		c.orig_biz_serial_no  ,                                                         
		c.orig_taker_code  ,                                                        
		c.collect_status   ,                                                                                                               
		c.order_by_no      ,                                                        
		c.detail_no        ,                                                         
		c.orig_detail_no   ,
		
		d.fee_sn          , 
		d.fee_id          , 
		d.fee_name        , 
		d.fee_type_flag   , 
		d.serial_no       , 
		d.fee_category1   , 
		d.fee_category2   , 
		d.occur_date      , 
		d.org_code        , 
		d.org_name        , 
		d.currency        , 
		d.fee_amount     ,
		d.fee_cycle_id    , 
		d.fee_detail_id   , 
		d.create_type     , 
		d.last_update_date ,
		d.last_update_time ,
		d.gather_flag     , 
		d.need_gather     , 
		d.channel_serial_no ,
		d.create_date     , 
		d.result_code     , 
		d.result_info     ,
		d.detail_no       
		
		
	from 
	 ect888_ods_uat1.f_ccs_fee_jour_real a  left outer join	ect888_ods_uat1.f_ccs_fee_trade_core_process_real b on a.serial_no=b.process_id left outer join ect888_ods_uat1.f_ccs_fee_trade_core_real c  on b.fee_trade_sn=c.fee_trade_sn left outer join  ect888_ods_uat1.f_ccs_fenrun_jour_real d on a.serial_no= d.serial_no 
	where a.dt = '$date_dt' and b.dt = '$date_dt' and c.dt = '$date_dt' and d.dt = '$date_dt';
