
	alter table  o_his_ccs_fee_jour_union drop if     exists partition (dt = 'dtonly');
	alter table  o_his_ccs_fee_jour_union add  if not exists partition (dt = 'dtonly');

	insert into table  o_his_ccs_fee_jour_union partition( dt = 'dtonly' )
	select
		a.fee_sn              ,
		a.fee_id              ,
		a.fee_name            ,
		a.fee_type_flag       ,
		a.serial_no           ,
		a.fee_category1       ,
		a.fee_category2       ,
		a.occur_date          ,
		a.org_code            ,
		a.org_name            ,
		a.user_id             ,
		a.user_name           ,
		a.currency            ,
		a.occur_amount       ,
		a.standard_fare      ,
		a.fee_amount         ,
		a.favorable_amount   ,
		a.fee_cycle_id        ,
		a.fee_detail_id       ,
		a.create_type         ,
		a.last_update_date    ,
		a.last_update_time    ,
		a.gather_flag         ,
		a.need_gather         ,
		a.result_code         ,
		a.result_info         ,
		a.tohis_date          ,
		a.channel_serial_no   ,
		a.create_date         ,
		a.fees_base_type     ,
		a.detail_no   	  ,

		b.process_id      ,  
		b.fee_trade_sn    ,  
		b.fee_id          ,  
		b.fee_category1   ,  
		b.fee_category2   ,  
		b.fee_org_code    ,  
		b.taker_code      ,  
		b.transferee_code ,  
		b.transferor_code ,  
		b.trade_amount    , 
		b.currency        ,  
		b.trade_date      ,  
		b.trade_time      ,  
		b.compute_status  ,  
		b.include_count_favorable ,
		b.input_date      ,  
		b.input_time      ,  
		b.remark          ,  
		b.reserve1        ,  
		b.reserve2        ,
		b.tohis_date		,    
		b.trading_channel ,  
		b.channel_serial_no ,
		b.order_by_no     ,  
		b.multitem_flag   ,
		b.detail_no       ,

		c.fee_trade_sn     ,                                                         
		c.fee_category1    ,                                                         
		c.fee_category2    ,                                                        
		c.busi_type        ,            
		c.busi_mark        ,                                                         
		c.msg_no           ,                                                         
		c.biz_serial_no    ,                                                         
		c.channel_serial_no  ,                                                         
		c.currency         ,                                                         
		c.trade_amount     ,                                                        
		c.trade_date       ,                                                         
		c.trade_time       ,                                                         
		c.taker            ,                                                         
		c.taker_code       ,                                                         
		c.taker_sub        ,                                                         
		c.transferee       ,                                                         
		c.transferee_code  ,                                                         
		c.transferee_sub   ,                                                         
		c.transferor       ,                                                         
		c.transferor_code  ,                                                         
		c.transferor_sub   ,                                                         
		c.record_status    ,                                                         
		c.trade_type_status  ,                                                       
		c.compute_status   ,                                                         
		c.remark           ,                                                         
		c.reserve1         ,                                                        
		c.reserve2         ,                                                         
		c.merchants_type   ,                                                         
		c.trading_channel  ,                                                         
		c.collect_date     ,                                                         
		c.orig_busi_type   ,                                                         
		c.orig_busi_mark   ,                                                         
		c.orig_msg_no      ,                                                         
		c.orig_biz_serial_no  ,                                                         
		c.orig_taker_code  ,                                                        
		c.collect_status   ,                                                         
		c.tohis_date       ,                                                         
		c.order_by_no      ,                                                        
		c.detail_no        ,                                                         
		c.orig_detail_no   ,
		
		
		d.process_id 		,
		d.fee_trade_sn 		,
		d.fee_id 			,
		d.fee_category1 		,
		d.fee_category2 		,
		d.fee_org_code 		,
		d.taker_code 		,
		d.transferee_code 	,
		d.transferor_code 	,
		d.trade_amount 		,
		d.currency 			,
		d.trade_date 		,
		d.trade_time 		,
		d.account_type 		,
		d.detail_type 		,
		d.compute_status 	,
		d.include_count_favorable ,
		d.input_date 		,
		d.input_time 		,
		d.remark 			,
		d.reserve1 			,
		d.reserve2 			,
		d.tohis_date 		,
		d.channel_serial_no 	,
		d.order_by_no 		,
		d.multitem_flag 		,
		
		e.fee_trade_sn     ,                                                         
		e.data_from        ,                                                         
		e.fee_category1    ,                                                         
		e.fee_category2    ,                                                         
		e.biz_serial_no    ,                                                         
		e.channel_serial_no  ,                                                         
		e.currency         ,                                                         
		e.trade_amount     ,                                                        
		e.trade_date       ,                                                         
		e.trade_time       ,                                                         
		e.taker            ,                                                         
		e.taker_code       ,                                                         
		e.taker_sub        ,                                                         
		e.transferee       ,                                                         
		e.transferee_code  ,                                                         
		e.transferee_sub   ,                                                         
		e.transferor       ,                                                         
		e.transferor_code  ,                                                      
		e.transferor_sub   ,                                                         
		e.record_status    ,                                                         
		e.trade_type_status  ,                                                         
		e.account_no       ,                                                         
		e.account_type     ,                                                         
		e.detail_type      ,                                                         
		e.compute_status   ,                                                         
		e.remark           ,                                                         
		e.reserve1         ,                                                         
		e.reserve2         ,                                                         
		e.collect_date     ,                                                         
		e.tohis_date       ,                                                         
		e.order_by_no      

		
	from 
	 ect888_ods_uat1.f_ccs_his_fee_jour a left outer join ect888_ods_uat1.f_ccs_his_fee_trade_core_process b on  a.serial_no=b.process_id left outer join ect888_ods_uat1.f_ccs_his_fee_trade_core c on b.fee_trade_sn=c.fee_trade_sn left outer join ect888_ods_uat1.f_ccs_his_fee_trade_credit_process  d on a.serial_no =d.process_id left outer join ect888_ods_uat1.f_ccs_his_fee_trade_credit e on d.fee_trade_sn = e.fee_trade_sn 

	where a.dt = '$date_dt';
